### ISSUE TITLE
高德地图用不了getGaoDeMap功能

### ISSUE THREAD

**Issue by qq19880123456** [icejean/gaodemap#1]
您好，谢谢您的高德地图包。
我想用此包画出地图，但是用不了。谢谢您指点一下。（电脑网络很好，可以用google 和观看Youtube 视频，应该不是网络问题）

下面是我用的命令。
library(gaodemap)
options(gaode.key = 'my key')
p <- getGaoDeMap('beijing')
ggmap(p)

但是出现了下面的信息：
试开URL’https://restapi.amap.com/v3/staticmap?size=400*400&location=NA,NA&zoom=10&key=my key&scale=2'
Error in download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") : 
  无法打开URL'https://restapi.amap.com/v3/staticmap?size=400*400&location=NA,NA&zoom=10&key=my key&scale=2'
此外: Warning messages:
1: In trans(result) : 强制改变过程中产生了NA
2: In trans(result) : 强制改变过程中产生了NA
3: In download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") :
  cannot open URL 'https://restapi.amap.com/v3/staticmap?size=400*400&location=NA,NA&zoom=10&key=my key&scale=2': HTTP status was '500 Internal Server Error'

**Comment by icejean** [comment]
你先跑一下github上的示例程序，我刚跑了一遍，没有问题。记得把key换成你的，先跑简单的例子，确认账号网络等设置没有问题。
https://github.com/icejean/gaodemap/blob/master/tests/%E9%AB%98%E5%BE%B7%E5%9C%B0%E5%9B%BE%E7%A4%BA%E4%BE%8B.R
然后跑你自己的程序的话，可以用Rstudio的debug功能跟踪一下，看看是什么问题。可能是你传进去的参数不正确，试下传汉字完整的地名，
比如从省到市到县区街道的完整地名，可以用地址查询找出来再作为参数传进去。
#地址查询
## colleges in beijing
bj_college = getPlace('大学', '北京')

#获取静态地图，注意增加了变焦调整参数，以使静态地图与前面的矢量地图匹配，矢量地图刚好覆盖静态地图
q <- getGaoDeMap('珠海市', width=800, height=800, zoom=8, scale = 2)
ggmap(q)

**Comment by qq19880123456** [comment]
非常谢谢你的及时回复，终于正常运行了。
运行下面三个命令后就可以了
gaodeKey<-"..."
options(gaode.key='...')
getOption("gaode.key")

可以顺便问一下，除了查询中文地址，英文的地址现在支持吗？

**Comment by icejean** [comment]
没有测试过，国内地图好像都是中文的？
